"""add workspace_id to project

Revision ID: 3529daf4a281
Revises: 13d476f71969
Create Date: 2026-09-11 13:41:29.987535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3529daf4a281'
down_revision: Union[str, Sequence[str], None] = '13d476f71969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('workspace_id', sa.String(length=36), nullable=False))
    op.alter_column('project', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('project', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_project_workspace_id'), 'project', ['workspace_id'], unique=False)
    op.create_index('ix_project_workspace_status', 'project', ['workspace_id', 'status'], unique=False)
    op.create_foreign_key(None, 'project', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_members_ibfk_2'), 'project_members', type_='foreignkey')
    op.drop_constraint(op.f('project_members_ibfk_1'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_token', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('ticket', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ticket', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('workspace', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('workspace_memberships', 'role',
               existing_type=mysql.ENUM('workspace_admin', 'member', 'guest'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workspace_memberships', 'joined_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_memberships', 'joined_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('workspace_memberships', 'role',
               existing_type=mysql.ENUM('workspace_admin', 'member', 'guest'),
               server_default=sa.text("'member'"),
               existing_nullable=False)
    op.alter_column('workspace', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('workspace', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('ticket', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('ticket', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('refresh_token', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_ibfk_1'), 'project_members', 'project', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_members_ibfk_2'), 'project_members', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_index('ix_project_workspace_status', table_name='project')
    op.drop_index(op.f('ix_project_workspace_id'), table_name='project')
    op.alter_column('project', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('project', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('project', 'workspace_id')
    # ### end Alembic commands ###
