"""again added_owner_id_from_workspace

Revision ID: 8f292b92b48d
Revises: f6056f00005b
Create Date: 2026-05-06 12:22:57.405476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f292b92b48d'
down_revision: Union[str, Sequence[str], None] = 'f6056f00005b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workspace_memberships_ibfk_3'), 'workspace_memberships', type_='foreignkey')
    op.drop_column('workspace_memberships', 'invited_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_memberships', sa.Column('invited_by', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('workspace_memberships_ibfk_3'), 'workspace_memberships', 'user', ['invited_by'], ['id'])
    # ### end Alembic commands ###
