"""add description to workspace

Revision ID: e28c5575d9d5
Revises: 100a933d0537
Create Date: 2026-05-02 18:15:34.049404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e28c5575d9d5'
down_revision: Union[str, Sequence[str], None] = '100a933d0537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('workspace', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('workspace', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('workspace', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.create_unique_constraint('uq_owner_workspace_name', 'workspace', ['owner_id', 'name'])
    op.add_column('workspace_memberships', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('workspace_memberships', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_memberships', 'left_at')
    op.drop_column('workspace_memberships', 'is_active')
    op.drop_constraint('uq_owner_workspace_name', 'workspace', type_='unique')
    op.alter_column('workspace', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('workspace', 'updated_at')
    op.drop_column('workspace', 'is_active')
    op.drop_column('workspace', 'description')
    # ### end Alembic commands ###
