"""add refresh_token improvements: index, cascade, revoked_at

Revision ID: e70dff1032df
Revises: b81efa7fb61b
Create Date: 2026-08-31 19:44:23.007035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e70dff1032df'
down_revision: Union[str, Sequence[str], None] = 'b81efa7fb61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_token', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('refresh_token', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.drop_constraint(op.f('refresh_token_ibfk_1'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_token_ibfk_1'), 'refresh_token', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.alter_column('refresh_token', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('refresh_token', 'last_used_at')
    op.drop_column('refresh_token', 'revoked_at')
    # ### end Alembic commands ###
