"""initial_migration

Revision ID: f6056f00005b
Revises: e28c5575d9d5
Create Date: 2026-05-04 18:48:37.557119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6056f00005b'
down_revision: Union[str, Sequence[str], None] = 'e28c5575d9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_memberships', sa.Column('invited_by', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'workspace_memberships', 'user', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_memberships', type_='foreignkey')
    op.drop_column('workspace_memberships', 'invited_by')
    # ### end Alembic commands ###
